### ISSUE TITLE
Cannot open source file: 'pydem\cyfuncs\cyutils.c'

### ISSUE THREAD

**Issue by sahiggin** [creare-com/pydem#3] opened 2015-10-28 19:41 UTC
Hi there,

I am trying to install pydem on a Windows 7 system, and I am getting the error "Cannot open source file: 'pydem\cyfuncs\cyutils.c'" Is that something that should be copied from my cython installation, or should that come with the pydem download?

Thanks,
Stephanie

**Comment by mpu-creare** [comment] 2015-11-10 13:29
Hi Stephanie, 

pydem\cyfuncs\cyutils.c should be generated by cython when pydem is installed. 

Can you send me the output of your console when you're installing the software?

**Comment by mpu-creare** [comment] 2015-12-14 14:25
@sahiggin did you manage to get this resolved?

**Comment by mpu-creare** [comment] 2016-01-11 17:05
I'm closing this one because I didn't hear back. I'm happy to reopen if anyone can reproduce.

**Closed by mpu-creare** 2016-01-11 17:05 UTC
